import type {
  Article,
  CategoryColumn,
  CategoryMenuItem,
  CategoryMenuMega,
  EditorSidebarEntry,
  FeaturedPlayerVideo,
  MostReadRow,
  MostReadTab,
  SocialLinkItem,
  VideoTeaserData,
} from '../../homepage/models/news-ui.model';
import type { RectangleAdInput } from '../../models/story-teaser.model';

import { JA_SAMPLE_VIDEO_EMBED } from '../../content/shared-video.data';

/** Shared iframe payload for `data-video` on legacy JA video teasers. */
export { JA_SAMPLE_VIDEO_EMBED };

/** @deprecated Use {@link HOME_SIDEBAR_AD} from `home-page.data` — kept for scripts referencing this symbol. */
export const HOME_SIDEBAR_RECTANGLE_BANNER: RectangleAdInput = {
  imageSrc: '/images/banner-2.jpg',
  imageAlt: 'Sidebar 1',
  width: 300,
  height: 250,
  externalHref: '#',
  title: 'Sidebar 1',
};

export const worldMenuItems: CategoryMenuItem[] = [
  { title: 'Africa', link: '/article' },
  { title: 'Americas', link: '/article' },
  { title: 'Asia Pacific', link: '/article' },
  { title: 'Europe', link: '/article' },
  { title: 'Middle East', link: '/article' },
];

export const worldBigArticles: Article[] = [
  {
    imageSrc: '/images/news-35.jpg',
    imageAlt: '2018 FIFA World Cup Russia™ - Qualifiers - Africa',
    categoryLabel: 'Africa',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: '2018 FIFA World Cup Russia™ - Qualifiers - Africa',
    titleLink: '/article',
    intro:
      'Morbi interdum magna sed ipsum vehicula, id tincidunt sapien hendrerit. Pellentesque euismod iaculis mi, id viverra eros cursus sed. Lorem ipsum...',
    leadClearfix: true,
    imageWrapperClass: 'pull- item-image',
  },
  {
    imageSrc: '/images/news-41.jpeg',
    imageAlt: "A woman's burden in war-torn South Sudan",
    categoryLabel: 'Middle East',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: "A woman's burden in war-torn South Sudan",
    titleLink: '/article',
    intro:
      'Vuas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et...',
    leadClearfix: true,
    imageWrapperClass: 'pull-left item-image',
  },
];

export const worldNormalArticles: Article[] = [
  {
    imageSrc: '/images/news-36.jpg',
    imageAlt: 'Africa Travel | African Tours: Safari, Egypt, Morocco Trips',
    categoryLabel: 'Africa',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Africa Travel | African Tours: Safari, Egypt, Morocco Trips',
    titleLink: '/article',
    teaserClear: true,
    imageWrapperClass: 'pull- item-image',
  },
  {
    imageSrc: '/images/news-40.jpeg',
    imageAlt: 'Americas Best Value Inns & Suites',
    categoryLabel: 'Americas',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Americas Best Value Inns & Suites',
    titleLink: '/article',
    imageWrapperClass: 'pull- item-image',
  },
  {
    imageSrc: '/images/news-39.jpeg',
    imageAlt: 'Americas Society and Council of the Americas',
    categoryLabel: 'Americas',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Americas Society and Council of the Americas',
    titleLink: '/article',
    teaserClear: true,
    imageWrapperClass: 'pull- item-image',
  },
  {
    imageSrc: '/images/news-46.jpeg',
    imageAlt: "Asia Pacific's Latest Business News, Sector Watch News",
    categoryLabel: 'Asia Pacific',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: "Asia Pacific's Latest Business News, Sector Watch News",
    titleLink: '/article',
    imageWrapperClass: 'pull- item-image',
  },
];

export const sportMenuItems: CategoryMenuItem[] = [
  { title: 'NFL', link: '/article' },
  { title: 'NBA', link: '/article' },
  { title: 'Soccer', link: '/article' },
  { title: 'Boxing', link: '/article' },
  { title: 'Tennis', link: '/article' },
];

export const sportLeadArticle: Article = {
  imageSrc: '/images/boxing-4.jpeg',
  imageAlt: "'No deadline' for GGG-Canelo",
  categoryLabel: 'Boxing',
  categoryLink: '/article',
  dateLine: 'Mar 9, 2022',
  title: "'No deadline' for GGG-Canelo",
  titleLink: '/article',
  intro:
    'Morbi tristique senectus turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam...',
  leadClearfix: false,
  imageWrapperClass: 'pull-left item-image',
};

export const sportSidebarArticles: Article[] = [
  {
    imageSrc: '/images/nba-1.jpeg',
    imageAlt: 'Carroll takes aim at West Ham fans for leaving games early',
    categoryLabel: 'NBA',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Carroll takes aim at West Ham fans for leaving games early',
    titleLink: '/article',
    teaserClear: true,
    imageWrapperClass: 'pull-left item-image',
  },
  {
    imageSrc: '/images/soccer-5.jpeg',
    imageAlt: 'Chelsea proved they are still behind Conte with United win - Neville',
    categoryLabel: 'Soccer',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Chelsea proved they are still behind Conte with United win - Neville',
    titleLink: '/article',
    imageWrapperClass: 'pull-left item-image',
  },
  {
    imageSrc: '/images/nfl-2.jpeg',
    imageAlt: 'Coleman: Williams is a fighter',
    categoryLabel: 'NFL',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Coleman: Williams is a fighter',
    titleLink: '/article',
    teaserClear: true,
    imageWrapperClass: 'pull-left item-image',
  },
  {
    imageSrc: '/images/nba-4.jpeg',
    imageAlt: 'England ring changes for France',
    categoryLabel: 'NBA',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'England ring changes for France',
    titleLink: '/article',
    imageWrapperClass: 'pull-left item-image',
  },
];

export const entertainmentMenuItems: CategoryMenuItem[] = [
  { title: 'Movie', link: '/article' },
  { title: 'Music', link: '/article' },
  { title: 'TV Show', link: '/article' },
];

export const entertainmentLeadArticle: Article = {
  imageSrc: '/images/news-21.jpeg',
  imageAlt: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
  categoryLabel: 'Movie',
  categoryLink: '/article',
  dateLine: 'Mar 9, 2022',
  title: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
  titleLink: '/article',
  intro:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula mi ex, feugiat ultrices enim tincidunt eget. Sed leo eros, faucibus at...',
  leadLayout: 'wide',
  imageWrapperClass: 'pull-left item-image',
};

export const entertainmentSidebarArticles: Article[] = [
  {
    imageSrc: '/images/tvshow-1.jpeg',
    imageAlt: 'Bikini Kill Reunite for First Live Performance in 20 Years',
    categoryLabel: 'TV Show',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'Bikini Kill Reunite for First Live Performance in 20 Years',
    titleLink: '/article',
    intro: '',
    imageWrapperClass: 'pull-left item-image',
  },
  {
    imageSrc: '/images/news-7.jpg',
    imageAlt: 'Breaking Celeb News, Entertainment News, and Celebrity Gossip',
    categoryLabel: 'Entertaiment',
    categoryLink: '/',
    dateLine: 'Mar 9, 2022',
    title: 'Breaking Celeb News, Entertainment News, and Celebrity Gossip',
    titleLink: '/article',
    intro: '',
    imageWrapperClass: 'pull-left item-image',
  },
  {
    imageSrc: '/images/news-17.jpeg',
    imageAlt: 'EU citizens explain why they are leaving the UK',
    categoryLabel: 'Movie',
    categoryLink: '/article',
    dateLine: 'Mar 9, 2022',
    title: 'EU citizens explain why they are leaving the UK',
    titleLink: '/article',
    intro: '',
    imageWrapperClass: 'pull-left item-image',
  },
];

export const techMenuItems: CategoryMenuItem[] = [
  { title: 'Politics', link: '/category/world' },
  { title: 'Business', link: '/category/world' },
  { title: 'World', link: '/category/world' },
  { title: 'Tech', link: '/category/world' },
  { title: 'Sport', link: '/category/world' },
  { title: 'Entertainment', link: '/category/world' },
];

export const techMegaMenu: CategoryMenuMega = {
  moreLabel: 'More',
  items: [
    { title: 'Food', link: '/gallery' },
    { title: 'Election 2017', link: '/article' },
    { title: 'Debating', link: '/article' },
    { title: 'Opinion', link: '/article' },
    { title: 'Market', link: '/article' },
    { title: 'Personal Finance', link: '/article' },
    { title: 'Technology', link: '/article' },
    { title: 'Africa', link: '/article' },
    { title: 'Americas', link: '/article' },
    { title: 'Asia Pacific', link: '/article' },
    { title: 'Europe', link: '/article' },
    { title: 'Middle East', link: '/article' },
    { title: 'Computer', link: '/subcategory' },
    { title: 'Tech Tip', link: '/subcategory' },
    { title: 'Personal Tech', link: '/article' },
    { title: 'Mobile', link: '/article' },
    { title: 'NFL', link: '/article' },
    { title: 'NBA', link: '/article' },
    { title: 'Soccer', link: '/article' },
    { title: 'Boxing', link: '/article' },
    { title: 'Tennis', link: '/article' },
    { title: 'Movie', link: '/article' },
    { title: 'Music', link: '/article' },
    { title: 'TV Show', link: '/article' },
    { title: 'Cooking', link: '/gallery' },
    { title: 'Restaurant', link: '/gallery' },
    { title: 'Stress Foods', link: '/gallery' },
    { title: "Fashion & Style", link: '/gallery' },
    { title: "Men's Style", link: '/gallery' },
    { title: "Women's Style", link: '/gallery' },
    { title: 'Wedding', link: '/gallery' },
  ],
};

export const techSliderArticles: Article[] = [
  {
    imageSrc: '/images/news-1.jpg',
    imageAlt: 'Donald Trump Threatens to Sue The Times Over Article on Unwanted  Advances',
    categoryLabel: 'World',
    categoryLink: '/category/world',
    dateLine: 'Mar 9, 2022',
    title: 'Donald Trump Threatens to Sue The Times Over Article on Unwanted  Advances',
    titleLink: '/article',
    categoryBgClass: 'bg-cat-blue',
    imageTitle: 'Donald Trump Threatens to Sue The Times Over Article on Unwanted  Advances',
  },
  {
    imageSrc: '/images/news-21.jpeg',
    imageAlt: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
    categoryLabel: 'Food',
    categoryLink: '/gallery',
    dateLine: 'Mar 9, 2022',
    title: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
    titleLink: '/article',
    categoryBgClass: 'bg-cat-purple',
    imageTitle: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
  },
  {
    imageSrc: '/images/news-3.jpg',
    imageAlt: "Apple fires employee after daughter's video of iPhone X goes viral",
    categoryLabel: 'Tech',
    categoryLink: '/category/world',
    dateLine: 'Mar 9, 2022',
    title: "Apple fires employee after daughter's video of iPhone X goes viral",
    titleLink: '/article',
    categoryBgClass: 'bg-cat-cyan',
    imageTitle: "Apple fires employee after daughter's video of iPhone X goes viral",
    videoDuration: '2:38',
    slideVideo: {
      dataUrl: '/article',
      dataTitle: "Apple fires employee after daughter's video of iPhone X goes viral",
      dataVideo: JA_SAMPLE_VIDEO_EMBED,
      imageSrc: '/images/news-3.jpg',
      imageAlt: "Apple fires employee after daughter's video of iPhone X goes viral",
      title: "Apple fires employee after daughter's video of iPhone X goes viral",
      titleLink: '/article',
    },
  },
  {
    imageSrc: '/images/news-6.jpg',
    imageAlt: 'NewsNow: Sport news | Breaking News & Search 24/7',
    categoryLabel: 'Sport',
    categoryLink: '/category/world',
    dateLine: 'Mar 9, 2022',
    title: 'NewsNow: Sport news | Breaking News & Search 24/7',
    titleLink: '/article',
    categoryBgClass: 'bg-cat-green',
    imageTitle: 'NewsNow: Sport news | Breaking News & Search 24/7',
  },
  {
    imageSrc: '/images/news-7.jpg',
    imageAlt: 'Breaking Celeb News, Entertainment News, and Celebrity Gossip',
    categoryLabel: 'Entertaiment',
    categoryLink: '/',
    dateLine: 'Mar 9, 2022',
    title: 'Breaking Celeb News, Entertainment News, and Celebrity Gossip',
    titleLink: '/article',
    categoryBgClass: 'bg-cat-yellow',
    imageTitle: 'Breaking Celeb News, Entertainment News, and Celebrity Gossip',
  },
  {
    imageSrc: '/images/news-13.jpeg',
    imageAlt: 'Spain on the brink: VIOLENCE erupts as police chief sacked',
    categoryLabel: 'Food',
    categoryLink: '/gallery',
    dateLine: 'Mar 9, 2022',
    title: 'Spain on the brink: VIOLENCE erupts as police chief sacked',
    titleLink: '/article',
    categoryBgClass: 'bg-cat-purple',
    imageTitle: 'Spain on the brink: VIOLENCE erupts as police chief sacked',
  },
  {
    imageSrc: '/images/news-14.jpeg',
    imageAlt: "Labour MP who said Remain voters better educated 'has facts on side'",
    categoryLabel: 'Food',
    categoryLink: '/gallery',
    dateLine: 'Mar 9, 2022',
    title: "Labour MP who said Remain voters better educated 'has facts on side'",
    titleLink: '/article',
    categoryBgClass: 'bg-cat-purple',
    imageTitle: "Labour MP who said Remain voters better educated 'has facts on side'",
  },
];

export const sidebarSliderArticles: Article[] = [
  {
    imageSrc: '/images/news-9.jpeg',
    imageAlt: "'Free' illegal downloads could cost you big in malware",
    categoryLabel: 'Opinion',
    categoryLink: '/article',
    dateLine: '',
    title: "'Free' illegal downloads could cost you big in malware",
    titleLink: '/article',
    categoryBgClass: 'bg-cat-purple',
    imageTitle: "'Free' illegal downloads could cost you big in malware",
  },
  {
    imageSrc: '/images/boxing-4.jpeg',
    imageAlt: "'No deadline' for GGG-Canelo",
    categoryLabel: 'Boxing',
    categoryLink: '/article',
    dateLine: '',
    title: "'No deadline' for GGG-Canelo",
    titleLink: '/article',
    categoryBgClass: 'bg-cat-green',
    imageTitle: "'No deadline' for GGG-Canelo",
  },
  {
    imageSrc: '/images/news-25.jpeg',
    imageAlt: "10 Best Markets in Vietnam - Vietnam's Most Popular Local Markets",
    categoryLabel: 'Market',
    categoryLink: '/article',
    dateLine: '',
    title: "10 Best Markets in Vietnam - Vietnam's Most Popular Local Markets",
    titleLink: '/article',
    categoryBgClass: 'bg-cat-orange',
    imageTitle: "10 Best Markets in Vietnam - Vietnam's Most Popular Local Markets",
  },
  {
    imageSrc: '/images/news-4.jpg',
    imageAlt: '126 million Americans may have seen Russia-linked political posts',
    categoryLabel: 'Election 2017',
    categoryLink: '/article',
    dateLine: '',
    title: '126 million Americans may have seen Russia-linked political posts',
    titleLink: '/article',
    categoryBgClass: 'bg-cat-purple',
    imageTitle: '126 million Americans may have seen Russia-linked political posts',
  },
];

export const editorLeadArticle: Article = {
  imageSrc: '/images/news-9.jpeg',
  imageAlt: "'Free' illegal downloads could cost you big in malware",
  categoryLabel: '',
  categoryLink: '/article',
  dateLine: 'Mar, 09 2022',
  title: "'Free' illegal downloads could cost you big in malware",
  titleLink: '/article',
  intro: '',
  leadLayout: 'flow',
  metaAfterTitle: true,
  imageWrapperClass: 'pull-left item-image',
};

export const editorArticles: EditorSidebarEntry[] = [
  {
    kind: 'article',
    item: {
      imageSrc: '/images/news-4.jpg',
      imageAlt: '126 million Americans may have seen Russia-linked political posts',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: '126 million Americans may have seen Russia-linked political posts',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
  },
  {
    kind: 'video',
    item: {
      imageSrc: '/images/news-40.jpeg',
      imageAlt: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
      titleLink: '/article',
    },
    video: {
      dataUrl:
        '/index.php/politics/20-debating/80-amanda-knox-says-she-was-never-allowed-to-mourn-meredith-kercher',
      dataTitle: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
      dataVideo: JA_SAMPLE_VIDEO_EMBED,
      imageSrc: '/images/news-40.jpeg',
      imageAlt: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
      title: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
      titleLink: '/article',
      dateLine: 'Mar, 09 2022',
    },
  },
  {
    kind: 'article',
    item: {
      imageSrc: '/images/news-10.jpg',
      imageAlt: 'Asia trip is a chance for Trump to act like a leader',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: 'Asia trip is a chance for Trump to act like a leader',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
  },
];

const mostReadWeekRows: MostReadRow[] = [
  {
    kind: 'image',
    rank: 1,
    accentClass: 'link-cat-yellow',
    article: {
      imageSrc: '/images/news-14.jpeg',
      imageAlt: "Labour MP who said Remain voters better educated 'has facts on side'",
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: "Labour MP who said Remain voters better educated 'has facts on side'",
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
  {
    kind: 'image',
    rank: 2,
    accentClass: 'link-cat-orange',
    article: {
      imageSrc: '/images/news-16.jpeg',
      imageAlt: 'Business News and Financial News - CNNMoney',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: 'Business News and Financial News - CNNMoney',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull- item-image',
  },
  {
    kind: 'image',
    rank: 3,
    accentClass: 'link-cat-blue',
    article: {
      imageSrc: '/images/news-17.jpeg',
      imageAlt: 'Middle East Map / Map of the Middle East - Facts, Geography, History',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: 'Middle East Map / Map of the Middle East - Facts, Geography, History',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull- item-image',
  },
  {
    kind: 'image',
    rank: 4,
    accentClass: 'link-cat-purple',
    article: {
      imageSrc: '/images/news-13.jpeg',
      imageAlt: 'Spain on the brink: VIOLENCE erupts as police chief sacked',
      categoryLabel: '',
      categoryLink: '/gallery',
      dateLine: 'Mar, 09 2022',
      title: 'Spain on the brink: VIOLENCE erupts as police chief sacked',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
  {
    kind: 'image',
    rank: 5,
    accentClass: 'link-cat-green',
    article: {
      imageSrc: '/images/soccer-1.jpeg',
      imageAlt: 'Sowerby strike knocks out Chorley',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar, 09 2022',
      title: 'Sowerby strike knocks out Chorley',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
];

const mostReadMonthRows: MostReadRow[] = [
  {
    kind: 'image',
    rank: 1,
    accentClass: 'link-cat-orange',
    article: {
      imageSrc: '/images/news-28.jpeg',
      imageAlt: 'U.S.-based stock funds take in most cash since May',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'U.S.-based stock funds take in most cash since May',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
  {
    kind: 'image',
    rank: 2,
    accentClass: 'link-cat-yellow',
    article: {
      imageSrc: '/images/news-21.jpeg',
      imageAlt: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'Barack Obama Mourns Shimon Peres, and a Bygone Israel',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
  {
    kind: 'gallery',
    rank: 3,
    accentClass: 'link-cat-orange',
    galleryId: 'ja-gallery-list-188',
    photosLabel: ' 4 Photos',
    article: {
      imageSrc: '/images/news-13.jpeg',
      imageAlt: 'Suspendisse mauris nibh',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'Suspendisse mauris nibh',
      titleLink: '/article',
    },
    slides: [
      { href: '/images/news-13.jpeg', title: '' },
      { href: '/images/news-20.jpeg', title: '' },
      { href: '/images/news-16.jpeg', title: '' },
      { href: '/images/news-17.jpeg', title: '' },
    ],
  },
  {
    kind: 'image',
    rank: 4,
    accentClass: 'link-cat-cyan',
    article: {
      imageSrc: '/images/news-12.jpeg',
      imageAlt: 'News, tips and reviews from the experts on PCs, Windows',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'News, tips and reviews from the experts on PCs, Windows',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull- item-image',
  },
  {
    kind: 'image',
    rank: 5,
    accentClass: 'link-cat-green',
    article: {
      imageSrc: '/images/nfl-2.jpeg',
      imageAlt: 'Coleman: Williams is a fighter',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'Coleman: Williams is a fighter',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
];

const mostReadAllRows: MostReadRow[] = [
  {
    kind: 'image',
    rank: 1,
    accentClass: 'link-cat-green',
    article: {
      imageSrc: '/images/tennis-2.jpg',
      imageAlt: 'Heather Watson secures first tour win since Wimbledon',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'Heather Watson secures first tour win since Wimbledon',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
  {
    kind: 'image',
    rank: 2,
    accentClass: 'link-cat-orange',
    article: {
      imageSrc: '/images/news-16.jpeg',
      imageAlt: 'Business News and Financial News - CNNMoney',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'Business News and Financial News - CNNMoney',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull- item-image',
  },
  {
    kind: 'image',
    rank: 3,
    accentClass: 'link-cat-purple',
    article: {
      imageSrc: '/images/news-9.jpeg',
      imageAlt: "'Free' illegal downloads could cost you big in malware",
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: "'Free' illegal downloads could cost you big in malware",
      titleLink: '/article',
    },
    imageWrapperClass: 'pull-left item-image',
  },
  {
    kind: 'video',
    rank: 4,
    accentClass: 'link-cat-purple',
    article: {
      imageSrc: '/images/news-19.jpg',
      imageAlt: "British tourist: 'I gave New York terror suspect five stars on Uber'",
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: "British tourist: 'I gave New York terror suspect five stars on Uber'",
      titleLink: '/article',
    },
    video: {
      dataUrl:
        '/index.php/politics/20-debating/82-british-tourist-i-gave-new-york-terror-suspect-five-stars-on-uber',
      dataTitle: "British tourist: 'I gave New York terror suspect five stars on Uber'",
      dataVideo: JA_SAMPLE_VIDEO_EMBED,
      imageSrc: '/images/news-19.jpg',
      imageAlt: "British tourist: 'I gave New York terror suspect five stars on Uber'",
      title: "British tourist: 'I gave New York terror suspect five stars on Uber'",
      titleLink: '/article',
      dateLine: '',
    },
  },
  {
    kind: 'image',
    rank: 5,
    accentClass: 'link-cat-orange',
    article: {
      imageSrc: '/images/news-29.jpeg',
      imageAlt: 'Personal Finance Advice and Financial News',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: '',
      title: 'Personal Finance Advice and Financial News',
      titleLink: '/article',
    },
    imageWrapperClass: 'pull- item-image',
  },
];

export const mostReadTabs: MostReadTab[] = [
  { title: 'Week', tabTitleClass: 'first', rows: mostReadWeekRows },
  { title: 'Month', tabTitleClass: '', rows: mostReadMonthRows },
  { title: 'All', tabTitleClass: 'last', rows: mostReadAllRows },
];

export const categoryColumns: CategoryColumn[] = [
  {
    title: 'Gaming',
    accentGroupClass: 'link-cat-red',
    minHeightPx: 644,
    lead: {
      imageSrc: '/images/game-6.jpg',
      imageAlt: 'Capcom Made A Lot Of Money Recently ',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar 9, 2022',
      title: 'Capcom Made A Lot Of Money Recently ',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
    items: [
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'League of Legends World Championship',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Multiplayer FPS Squad is having a free weekend ',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Razer announces new peripherals',
        titleLink: '/article',
      },
    ],
  },
  {
    title: 'Fashion',
    accentGroupClass: 'link-cat-pink',
    minHeightPx: 644,
    lead: {
      imageSrc: '/images/fashtion-6.jpg',
      imageAlt: '15 Fashion and Beauty Trends',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar 9, 2022',
      title: '15 Fashion and Beauty Trends',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
    items: [
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Fashion News and Trends: Designers, Models, Style Guides',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'George Takei Speaks Out on Kevin Spacey Allegations',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Here’s Every Piece From the Just-Launched Erdem x H&M Collab',
        titleLink: '/article',
      },
    ],
  },
  {
    title: 'Lifestyle',
    accentGroupClass: 'link-default',
    minHeightPx: 644,
    lead: {
      imageSrc: '/images/filestyle-7.jpeg',
      imageAlt: 'Derby Day got really messy this year',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar 9, 2022',
      title: 'Derby Day got really messy this year',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
    items: [
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Horror story behind your clothes label',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Mistake you are making after exercise',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'On display: Monaco 37 by Fairmont Homes',
        titleLink: '/article',
      },
    ],
  },
  {
    title: 'Arts',
    accentGroupClass: 'link-default',
    minHeightPx: 644,
    lead: {
      imageSrc: '/images/arts-5.jpeg',
      imageAlt: 'A Tree-Like Figure Composed of Natural and Technological Elements ',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar 9, 2022',
      title: 'A Tree-Like Figure Composed of Natural and Technological Elements ',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
    items: [
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Brittle Skeletons Crocheted from Discarded Textiles',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Chandeliers Constructed From Recycled Plastic PET Bottles ',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Colorfully Embroidered Vintage Photos',
        titleLink: '/article',
      },
    ],
  },
  {
    title: 'Education',
    accentGroupClass: 'link-default',
    minHeightPx: 644,
    lead: {
      imageSrc: '/images/education-1.jpeg',
      imageAlt:
        'Celebrity mums turn to Scandinavian-inspired exercise classes to  brain-train their children',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar 9, 2022',
      title:
        'Celebrity mums turn to Scandinavian-inspired exercise classes to  brain-train their children',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
    items: [
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Nigerian government pulls funding for 150 university students ',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Oxford University worker',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Teach First boss claims',
        titleLink: '/article',
      },
    ],
  },
  {
    title: 'Health',
    accentGroupClass: 'link-default',
    minHeightPx: 644,
    lead: {
      imageSrc: '/images/health-7.jpeg',
      imageAlt: '10 Hard-Earned Lessons on Running a Marathon',
      categoryLabel: '',
      categoryLink: '/article',
      dateLine: 'Mar 9, 2022',
      title: '10 Hard-Earned Lessons on Running a Marathon',
      titleLink: '/article',
      imageWrapperClass: 'pull-left item-image',
    },
    items: [
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: '6 Diet and Fitness Fads You Need to Forget',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'House Tax Bill Would Kill Medical Deductions',
        titleLink: '/article',
      },
      {
        imageSrc: '',
        imageAlt: '',
        categoryLabel: '',
        categoryLink: '/article',
        dateLine: 'Mar 9, 2022',
        title: 'Red Cross: $6 Million for Ebola Fight Stolen Through Fraud',
        titleLink: '/article',
      },
    ],
  },
];

export const featuredPlayerVideo: FeaturedPlayerVideo = {
  posterSrc: '/images/news-40.jpeg',
  posterAlt: '',
  headline: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
};

export const videoSidebarList: VideoTeaserData[] = [
  {
    dataUrl:
      '/index.php/politics/20-debating/80-amanda-knox-says-she-was-never-allowed-to-mourn-meredith-kercher',
    dataTitle: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
    dataVideo: JA_SAMPLE_VIDEO_EMBED,
    imageSrc: '/images/news-40.jpeg',
    imageAlt: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
    title: 'Amanda Knox says she was never allowed to mourn Meredith Kercher ',
    titleLink: '/article',
    dateLine: 'Mar, 09 2022',
  },
  {
    dataUrl:
      '/index.php/politics/20-debating/82-british-tourist-i-gave-new-york-terror-suspect-five-stars-on-uber',
    dataTitle: "British tourist: 'I gave New York terror suspect five stars on Uber'",
    dataVideo: JA_SAMPLE_VIDEO_EMBED,
    imageSrc: '/images/news-19.jpg',
    imageAlt: "British tourist: 'I gave New York terror suspect five stars on Uber'",
    title: "British tourist: 'I gave New York terror suspect five stars on Uber'",
    titleLink: '/article',
    dateLine: 'Mar, 09 2022',
  },
  {
    dataUrl:
      '/index.php/politics/20-debating/22-ivanka-trump-sexual-harassment-should-never-be-tolerated',
    dataTitle: 'Ivanka Trump: Sexual harassment should never be tolerated',
    dataVideo: JA_SAMPLE_VIDEO_EMBED,
    imageSrc: '/images/news-14.jpeg',
    imageAlt: 'Ivanka Trump: Sexual harassment should never be tolerated',
    title: 'Ivanka Trump: Sexual harassment should never be tolerated',
    titleLink: '/article',
    dateLine: 'Mar, 09 2022',
  },
  {
    dataUrl:
      '/index.php/politics/20-debating/79-jailing-of-catalan-ministers-sparks-mass-protests-in-barcelona',
    dataTitle: 'Jailing of Catalan ministers sparks mass protests in Barcelona',
    dataVideo: JA_SAMPLE_VIDEO_EMBED,
    imageSrc: '/images/news-11.jpg',
    imageAlt: 'Jailing of Catalan ministers sparks mass protests in Barcelona',
    title: 'Jailing of Catalan ministers sparks mass protests in Barcelona',
    titleLink: '/article',
    dateLine: 'Mar, 09 2022',
  },
  {
    dataUrl:
      '/index.php/politics/20-debating/81-new-fast-track-drug-plan-will-speed-nhs-access-by-up-to-four-years',
    dataTitle: "New 'fast track' drug plan will speed NHS access by up to four years",
    dataVideo: JA_SAMPLE_VIDEO_EMBED,
    imageSrc: '/images/news-46.jpeg',
    imageAlt: "New 'fast track' drug plan will speed NHS access by up to four years",
    title: "New 'fast track' drug plan will speed NHS access by up to four years",
    titleLink: '/article',
    dateLine: 'Mar, 09 2022',
  },
];

export const socialLinks: SocialLinkItem[] = [
  {
    href: '#',
    title: 'Instagram',
    btnClass: 'btn instagram',
    iconClass: 'fa fa-instagram',
    label: 'Instagram',
  },
  {
    href: '#',
    title: 'Twitter',
    btnClass: 'btn twitter',
    iconClass: 'fa fa-twitter',
    label: 'Twitter',
  },
  {
    href: '#',
    title: 'YouTube',
    btnClass: 'btn youtube',
    iconClass: 'fa fa-youtube-play',
    label: 'YouTube',
  },
];
